# Generated by Django 5.0.6 on 2026-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
